[package]
name = "plugins_random"
version = "0.1.0"
authors = ["René Perschon <rperschon85@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-plugins-core = { path = "../core" }
reqwest = "0.9.21"
